<?php
require_once($_SERVER['DOCUMENT_ROOT'] . '/../includes/application_includes.php');
 
// Include the template files needed for the page
require_once(FS_TEMPLATES . 'mainHeaderTemplate.php');
require_once(FS_TEMPLATES . 'highlightedPostsTemplate.php');
require_once(FS_TEMPLATES . 'mainFooterTemplate.php');
require_once(FS_INCLUDES . 'post.php');
require_once(FS_TEMPLATES . 'postTemplate.php');
require_once(FS_TEMPLATES . 'admin.php');
	
	        // Load mocked up page content					
            $stories = [
                        ['id' => 1,
                            'title' => 'Michael Barone: Are Democrats destroying their own credibility?',
                            'content' => "You can’t expect a political party to be rigorously intellectually honest on any consistent basis. They’re trying to win elections—and to achieve policy results they genuinely believe to be desirable, and rigorous honesty sometimes has to take the back seat. And anyway, their embarrassed members will argue, the other side does it, and you can’t unilaterally disarm.
That said, it strikes me that the Democratic Party has been taken this to a self-harming extreme. For if the voters catch you stretching the truth and exaggerating the other side’s misdeeds, your credibility will suffer. Even when you state plain truths or make reasonable arguments, many people won’t, or will be reluctant to, believe you.
On what issues are Democrats taking such risks? (1) Their undisguised faith that Donald Trump and his campaign colluded with Vladimir Putin’s Russia to steal the 2016 election. Maybe I’m wrong, but I don’t think this happened or that it has or will come anywhere close to being proven.
(2) The Republican tax bill was a “scam” that was going to take money away from those with modest incomes. A look at the tax rate schedules in the Republicans’ bill should have told Democrats that this argument wasn’t sustainable, and perhaps they made it in the hope—which didn’t seem too far-fetched at the time—that enough Republicans would waver, the bill would never pass and their characterization, with predictable help from the mainstream media, would stick. But the bill passed, modest and low-income people are getting raises and bonuses, and just about everyone will get a bigger paycheck later this month.
(3) Their claims that the Republicans were responsible for shutting the government down last month over DACA. Democrats knew that DACA was widely popular, but overestimated its importance to voters. It turns out they didn’t want the government shut down to help even deserving illegal immigrants. It’s hard for the party of more government to lose an argument over who caused a government shutdown, but they managed to do it.
(4) Their arguments that release of the Nunes memo would endanger national security, when it was obvious to anyone who read the memo that it wouldn’t. And then there's their ludicrous supporting argument that you should never harm the image of the FBI. Democrats have long been willing to criticize the FBI and other law enforcement agencies when they think it will help them politically, or when they think there has genuine abuse; the first is understandable and the second often commendable. How is this different?
This looks very much like those who live in an anti-Trump cocoon have such utter contempt for their fellow citizens outside that cocoon that they expect them to fall for unsustainable arguments. They have the excuse of knowing that most of the mainstream media will do so, but they seem not to have learned that a very large part of the American electorate no longer has respect for or pays heed to the mainstream media.
Political debate requires understanding how persuasive—or unpersuasive—arguments are and will prove over time. I’m surprised that Democrats aren’t doing a better job at this, and I suspect they’re reducing their credibility with many voters they have been taking for granted.", 
                            'image' => 'assets/article1.jpg'
                        ],
                        ['id' => 2,
                            'title' => 'America Needs a Merit-Based Immigration System',
                            'content' => "For the last two decades, debates over immigration reform have largely focused on illegal immigration. In recent weeks, however, the debate has increasingly turned to proposals dealing with legal immigration and the way we award green cards, which allow immigrants to live and work permanently in the U.S.
At last week’s State of the Union address, President Trump outlined four “pillars” of his proposed immigration framework. The first two pillars deal with illegal immigration. The first calls for a pathway to citizenship for individuals brought illegally to the United States as children. The second calls for increased border security.
The framework’s third and fourth pillars are less familiar. They address legal immigration. The third pillar calls for ending the visa lottery, through which 50,000 individuals each year from countries with low rates of immigration to the United States receive green cards. The fourth pillar calls for revising current family-based immigration laws to reduce the number of green cards awarded on the basis of family connections.
Predictably, President’s Trump’s plan was met with howls of outrage on the left. Critics charged the president with showing animosity, not just toward illegal immigration, but toward legal immigration as well.
The notion that our legal immigration laws merit rethinking, however, is not anti-immigrant. Rather, it’s a question of allocation.
Through the visa lottery, we award 50,000 green cards each year based on country of origin. Through our current family-based immigration laws, we award hundreds of thousands of additional green cards on the basis of family connections. U.S. citizens and lawful permanent residents can sponsor parents, children, siblings, and others for green cards.
No one disputes that family relationships are extremely important. As the father of six children, I know as well as anyone the importance of family.
But that doesn’t mean family connections, or country of origin, should take priority over other considerations, like education or skill level, in awarding limited numbers of green cards.
Each year, far more people apply to enter our country than there are available green cards. This means we must choose who gets priority and who doesn’t.
And in our increasingly competitive, globalized economy, it’s entirely reasonable to ask whether an immigration system that focuses more on education and skills than on country of origin and family connections might better advance America’s interests.

Today American companies compete not just with each other, but with companies across the globe. Businesses need the best available talent to succeed, and America needs the world’s best and brightest to keep itself at the forefront of innovation.
That’s why I recently reintroduced my Immigration Innovation Act, or I-Squared, to ensure that employers are able to hire – and retain – workers with the skills they need. I-Squared does this by increasing the number of available high-skilled visas and by streamlining the process by which a skilled worker can transition to green card status.
I-Squared also simplifies the process by which students who come to the United States for college or graduate school can obtain permanent employment following graduation. Few things make less sense than welcoming bright, hard-working individuals to our country to be educated and then sending them back home to compete against us.
As we consider proposals to reform legal immigration, our focus needs to be on how we can design a system that better meets the needs of 21st century America. And high-skilled immigration must be at the center of that discussion.
We don’t need to reinvent the wheel here. We already have high-skilled immigration programs in our existing laws. Visa categories like EB1, EB2 and EB3, as well as H-1B, are designed for immigrants with in-demand skills.
In my view, an eminently reasonable resolution to the current debates about the visa lottery and family-based immigration would be to reallocate green cards currently set aside for the lottery and for parents, siblings, and adult children to high-skilled visa categories.
At the same time, we should take the opportunity to fix any flaws in these categories’ current structure. This commonsense approach would help ensure that we have a modern workforce with the skills employers need, while avoiding rabbit-hole discussions about overall levels of immigration that are likely to take us nowhere.
Let me be clear. I’m not calling for any reduction in legal immigration. Legal immigration always has been, and always will be, essential to our country’s success and economic prosperity. Moreover, there is no way that any immigration proposal that contains cuts to legal immigration will attain sufficient congressional support to become law.
What I am calling for is a smarter, better calibrated legal immigration system that gives greater priority to education and skill level, just like my I-Squared bill does.
Now that the moment has come to talk about legal immigration, let’s be smart. Let’s talk about high-skilled immigration and how we can design a legal immigration system that will prepare our country for success for decades to come.",
                            'image' => 'assets/article2.jpg'
                        ],
                        ['id' => 3,
                            'title' => 'It’s Time for an Immigration Enchilada',
                            'content' => "I Immigration has been on the United States-Mexico agenda for years. In recent times, three American attempts at comprehensive immigration reform, which included amnesty for undocumented Mexicans in the United States and a temporary-worker visa program, have failed. A bilateral effort between 2001 and 2003 also collapsed.
Nothing affects Mexico more than United States immigration policy, and the centrality of the issue in American politics is more prominent than ever.
The most urgent challenge is to find a way forward for the so-called Dreamers, the beneficiaries of President Barack Obama’s Deferred Action for Childhood Arrivals program. Nearly 800,000 young people brought to the United States by their parents as children applied for and were given protected status by the Obama administration. Thanks to DACA, they no longer needed to fear deportation, were able to work legally and had realistic hopes that one day they would be on a path to citizenship in the only country they knew. More than three-fourths of the Dreamers are Mexican. That’s why people here follow their fate closely.
President Trump rescinded Mr. Obama’s DACA policy. He has proposed a four-pillar overhaul of American immigration policy that most Democrats and Latinos in the United States detest. Strangely enough, however, it might benefit Mexico, especially if it is accompanied by additional changes in the issuance of temporary-worker visas, and in particular those known as H-2A and H-2B.
The first pillar of Mr. Trump’s proposal — regularizing the status of the Dreamers and a million other young people who also could qualify for DACA status with a long and winding road to citizenship — works to Mexico’s advantage. Somewhere near 1.5 million of these young people are Mexican; that is roughly one-quarter of all undocumented Mexican citizens in the United States. Granting them the equivalent of amnesty, with the beacon of eventual citizenship, satisfies one of Mexico’s most crucial immigration demands.
The second pillar — $25 billion for a border wall — is obviously offensive to Mexico, but the country’s lame-duck president, Enrique Peña Nieto, has been much more adamant in his opposition to paying for the wall than to its actual construction. Mr. Peña Nieto either doesn’t believe it will ever see the light of day or lacks the backbone to oppose it. But Mr. Trump’s wall is something Mexico can simultaneously reject and live with, particularly if it will take years to build and if it merely complements segments of fences erected by Presidents Bill Clinton, George W. Bush and Obama. Mr. Trump’s third pillar is the most insulting for many Americans, since it eliminates the family reunification principle for accepting legal immigrants from abroad. Intended to deter “chain migration,” it would replace the family criterion with a merit-based system. In the future, only spouses and underage offspring (as opposed to parents and siblings today) of American citizens would be allowed permanent residence, and eventually citizenship. The net effect would be to “whiten” immigration and limit the share of Mexicans.
Since the largest group of foreigners applying for family reunification is by far Mexican (three times as many as Chinese citizens, for example), this would reduce the number of applicants from Mexico who get green cards. Nearly 200,000 Mexicans got green cards in fiscal year 2016; halving that number through a lengthy and tedious procedure that frustrates many Mexicans would not be as bad as shutting down the whole program.
The last pillar would suppress the lottery system that grants a small number of immigrant visas to applicants from underrepresented nations, mainly African. Again, this would surely “whiten” immigration and is thus a despicable proposal, but it does not affect Mexico. There is no lottery system for Mexicans.
So, viewed somewhat cynically from the perspective of strict Mexican national interests, the four-pillar plan has inconveniences for Mexico but also many advantages. That it is racist as well as unworthy of the American immigration ideal and inflames the worst demons in American society is another matter. As Mr. Trump says, countries have to look out for their own interests.
To make this plan attractive to Mexico, its leaders need to persuade the American president to increase the number of temporary-worker visas. Again, by far the largest number of these permits are extended to Mexicans. H-2A visas, for seasonal agricultural workers, have no congressional cap; H-2B visas, for seasonal nonagricultural activities, do, but it can be lifted and has been for several years. The Trump administration can increase these numbers significantly without congressional approval.
An immense reconstruction effort is underway in Texas and Florida after Hurricanes Harvey and Irma and, with virtual full employment, there is a huge demand for low-skilled, low-wage labor in those regions. It can come only from Mexico.
Were Mr. Peña Nieto to make such a suggestion and were Mr. Trump to accept it, both countries’ interests would be well served.
In the early years of this century, a comprehensive package like this was called “the whole enchilada.” Half a loaf, or whatever nutritional metaphor one prefers, is not bad.",
                            'image' => 'assets\article3.jpg'
                        ],
						['id' => 4,
                            'title' => 'Trump Signs Omnibus: Never Signing Another Spending Bill Like This Again',
                            'content' => "The president called a news conference on Twitter early Friday afternoon where he and several cabinet secretaries discussed the omnibus spending bill. Earlier on Friday the president tweeted that he might veto the bill that his budget director Mick Mulvaney grudgingly said the president would sign. \"I will never sign another bill like this again,\" the president said, calling for the Senate to get rid of the filibuster rule and give him a line-item veto: We have a lot of good news to report. Some tremendous trade deals are being made with various countries. We are negotiating very long, very hard, but very quickly.
And the deal with South Korea is -- according to Secretary Ross and Bob Lighthizer is very close to being finished. And we're going to have a -- a wonderful deal with a wonderful ally. We're getting very close to it. It was a deal that was causing a lot of problems for our country, in terms of employment and in terms of lots of other things.
I -- I might ask Secretary Ross to just say a few words about that, and then we're going to get on to this ridiculous situation that took place over the last week. 
So, Secretary Ross?
ROSS: Thank you, Mr. President.
We -- we believe we are relatively close to a pretty comprehensive resolution with the South Korean government. It will encompass, if it goes through, both the 232s and broader trade issues. And we hope by sometime next week to be able to have a real announcement.
TRUMP: Thank you very much, Wilbur. I appreciate it.
The last time we negotiated something like this -- and, as you know, it's always been a problem for our country. They get together, and they create a series of documents that nobody has been able to read, because it was -- it was just done.
Now, you tell me who can read that quickly? Takes a long time to read it.",
                            'image' => 'assets/article4.jpg'
                        ],
                        ['id' => 5,
                            'title' => 'How Feminists Became Democrats',
                            'content' => "By June 1980, Mary Dent Crisp began to suspect that her office was bugged. Crisp, the co-chairwoman of the Republican National Committee, had wondered for weeks why sensitive information appeared to be leaking from her Washington office to the press, and she noticed a beeping sound on the line during calls. She called in a private investigator to conduct a countersurveillance sweep of the office.
The investigator found no direct evidence of bugging but noted “two suspicious situations”: a wire running from a neighboring office through Crisp’s room to an unknown destination, and an electromagnetic “energy/radio field” detectable at a window near her desk. Crisp reported this to her fellow RNC officials. Three days later—an excessively long time, in her opinion—they called in another firm to investigate. That firm reported no evidence of surveillance. Eventually the police took over and concluded, after a seven-month investigation, that no bugging had taken place.
Although this case was deemed a false alarm, the idea that espionage might take place in a party committee’s headquarters would have hardly seemed farfetched just two presidential election cycles after the Watergate break-in. More notable was the fact that Crisp suspected the culprits to be members of her own party.
Crisp was a pro-choice, Equal Rights Amendment advocate locked in conflict with the Reagan campaign and its supporters. Her story—an RNC co-chair whose gradual professional isolation brought her to the point of suspecting skullduggery by factional enemies—captures in a vivid way a broader process that activists on the left and right helped to hasten during the 1970s: the partisan sorting of gender politics.
Positions on issues relating to women’s rights—from abortion to workplace justice to equality before the law—did not, as of the early 1970s, break down clearly along party lines. That began to change by the decade’s end, with feminist and antifeminist movement activists alike working to hasten the process. The untenable position in which Mary Crisp found herself in June 1980 resulted from the parties’ polarization in the preceding years.
Crisp’s story, drawn from archival material as well as contemporaneous journalistic accounts, takes on new resonance in our current political moment. Donald Trump ascended to the White House after an election that boasted the biggest gender gap on record, even as he simultaneously enjoyed enthusiastic support from a robust minority of women voters. (He won a majority of white women’s votes.) More striking, the opposition to Trump’s presidency—on the streets, on the ballot, and in the halls of Congress—has been dominated and defined by women. Women’s marches across the country bookended Trump’s first year in office, thousands of female candidates have jumped into electoral races at the local, state and federal level, and the #MeToo movement continues to rock politics and political culture just as it does other major institutions in American life.
The dynamics that enabled a man like Trump to capture the Republican Party have also shaped the nature of the resistance to his rule. And those dynamics can be traced back to the partisan sorting of feminism and antifeminism in the 1970s that caught Mary Crisp, along with so many others, in the crosswinds. 
Crisp was a career-long Republican and a feminist, and during her rise within party ranks, few perceived the combination to be contradictory. A former precinct captain in Maricopa County, Arizona, she served as a Republican national committeewoman during the Ford years and as the national convention secretary in 1976. Despite her support for President Gerald Ford in his nomination contest against Ronald Reagan that year, she encountered little opposition from Reaganites when newly elected RNC chairman Bill Brock chose her as party co-chair in January 1977.
Within months, however, Crisp’s penchant for candid press quotes drew their anger, beginning with her public criticism of Reagan’s “idea of purism” and her insistence that the Republican Party had to be able to encompass figures as ideologically disparate as Barry Goldwater and Jacob Javits.
The main focus of conservatives’ opposition to Crisp was her outspokenness on women’s rights. Her patron at the RNC, Mary Louise Smith, had managed to serve as the party’s first female chairwoman without controversy despite a reputation as, in one profiler’s words, an “ardent feminist.” But in the years since Smith took the reins in 1974, a powerful antifeminist movement had grown in coalition with other elements of the New Right. When Crisp, a member of President Carter’s National Advisory Committee for Women, spoke out for abortion rights, federal support for childcare, and redressing gender inequities in Social Security, or against job discrimination, those movement activists listened.
The Equal Rights Amendment was the key symbolic issue around which feminist and antifeminist forces mobilized for a fight in the mid to late 1970s, and Crisp’s pro-ERA advocacy galvanized conservative opposition to an intensity that Smith’s had not just a few years earlier. The National Women’s Conference, set to take place in honor of International Women’s Year, or IWY, in Houston in 1977, became a proving ground for both anti-ERA and antiabortion forces—ultimately marking, in historian Marjorie Spruill’s words, an “important turning point … in the evolution of American political culture” itself.
That March, Phyllis Schlafly, the powerful, shrewd leader of STOP ERA and the Eagle Forum, launched a new initiative called the IWY Citizens’ Review Committee. The project mobilized social and religious conservatives to participate in state delegate-selection conferences and to work to elect their own as delegates. A quarter of the Houston delegates ended up being conservatives.
One startled Republican feminist described what a typical mobilization looked like to Crisp. “The IWY at Nebraska was a disaster last weekend,” Pat Lahr Smith wrote to her in July. “The ‘Pro-Lifers’ rallied hundreds of people to drive into Lincoln on Sunday, register, and vote for their slate. That was the end of a balanced slate. Their slate was 500 votes ahead of the next names.” And for the conservative activists who did not make it into the national convention in Houston as delegates, Schlafly’s committee staged a 15,000-strong Pro-Life, Pro-Family Rally in the city during the proceedings.
The National IWY Commission’s draft resolutions featured a panoply of liberal feminist planks—not only endorsement of the ERA and abortion rights, but also federal aid for childcare, universal healthcare, and an end to discrimination based on sexual orientation. In the run-up to Houston, a Schlafly-led letter-writing campaign deluged public officials and convention delegates. Crisp, as both an Arizona delegate to the conference and an RNC official, hardly escaped. “I was appalled at the manner in which the Arizona IWY Convention was conducted,” one woman wrote to her, “and I am ashamed to know that you are a delegate of the IWY (at the same time as National Co-Chairman of the National Republican Party—my party).” Crisp was undaunted by the letters, pointing out in response to each of them that support for ERA ratification was part of the 1976 Republican Platform, as it had been for more than three decades.
The following year, after surviving an effort by Reagan aide Lyn Nofziger to replace her at the RNC, Crisp wrote to every Republican member of Congress to urge support for a bill that would extend the ERA ratification deadline. Her efforts outraged conservatives anew. They sent more streams of mail to her office and to Bill Brock’s. One ex-senator, George Murphy of California, articulated in a letter to Brock the partisan case against Crisp’s lobbying effort: “It is quite obvious that this is a liberal Democrat sponsored effort at best, and therefore, not in the Republican area for activity.” Brock would dutifully point out in response, just as Crisp did, that support for ERA ratification was a Republican platform position. But the center of gravity on gender issues was shifting so rapidly within the party by 1978 that the letter-writer’s arguments for what did and did not constitute a legitimate “Republican area for activity” were plausible. 
Polarization of the parties on gender issues took place rapidly and dramatically in the 1970s. As the political scientist Christina Wolbrecht has calculated, the percentage of House Democrats who co-sponsored legislation related to women’s rights began to exceed the figure for Republicans for the first time in 1972. The same interparty gap began to open in the Senate by 1978. Also starting in 1978, the difference in the National Women’s Political Caucus scores on women’s rights-related legislative votes earned by the median members of the two parties began to skyrocket—with Democrats scoring ever higher and Republican scores plummeting. The dueling gatherings in Houston in 1977, meanwhile, testified to the intensity of the polarization underway among grassroots activists.
As Crisp ran into these crosswinds, she became a source of growing irritation for Brock and his staff. In early 1979, Jimmy Carter removed Bella Abzug as the head of his National Advisory Committee for Women after Abzug openly criticized the president’s proposed budget cuts. The majority of the committee’s membership—including Crisp—resigned in protest of the firing. Conservative Republicans expressed befuddlement. “Why oh why did you resign just because that dreadful Bella was removed?” a Virginia woman asked her in a letter. Crisp “has permitted her interest in the radical women’s movement to overshadow her responsibility to the Republican Party,” the head of a Tennessee Republican Women’s Club insisted. A group of 10 congressmen wrote Brock to ask him to “please help us explain to Republicans in our Districts why the removal of Bella Abzug from any governmental body is not cause for rejoicing rather than regret and resignation.”
Brock began to keep Crisp at arm’s length at the RNC, with relations worsening in the summer of 1979 during the early planning stages for the national convention. In notes she prepared for a meeting in 1979 with Brock to resolve the issues, Crisp shared her frustration: “If my position is becoming impotent, I cannot sit back and let it happen.”
The presidential primary of 1980 worsened these tensions. As the Reagan campaign marched forcefully from state victory to state victory against his Republican competitors, Crisp grew increasingly vocal about the threat his candidacy would pose to the platform’s pro-ERA plank. Engagement with issues like ERA and abortion rights helped pique Crisp’s interest in John Anderson’s campaign. Anderson, an Illinois congressman, had run as a maverick social liberal in the primaries with little success; in March, he relaunched his presidential bid as an independent.
Three months later, with Reagan having all but secured the Republican nomination, Crisp shared her thoughts to a Chicago Sun-Times reporter in a fit of shockingly ill-advised candor. Supporting Anderson, she said, might pose a solution to the “big dilemma” facing pro-ERA women heading into a convention dominated by Reagan. Although she refrained from endorsing Anderson’s candidacy, she deemed his chances of winning the presidency “not so far-fetched.” She referred to his GOP credentials as “impeccable—he only refuses to say he’s content with Reagan’s way of looking at problems.”
Within a day of the publication of Crisp’s interview, Brock sent her a blistering memo that called her comments “wrong and totally inappropriate for a major party official.” To ensure that she “adopt the lowest profile possible” to avoid exacerbating the damage she had caused, Brock informed Crisp that he would eliminate her welcoming remarks from the convention program and cancel the two events she had been scheduled to host. Four days later, she informed her colleagues that she would not be seeking re-election as RNC co-chair.
A week after that came the intrigue surrounding the bugging scare in Crisp’s office. The police concluded that the electromagnetic field was normal for an office setting and the suspicious wire was likely the remnant of an interoffice bell system, but Crisp would never shake her conviction that she had been tapped. Brock made it clear that he thought her suspicions were unwarranted. Members of Reagan’s camp were happy to go further, offering sexist mockery through a veil of anonymity. When a Washington Post reporter asked an unnamed Reagan aide why Crisp might suspect that she was being surveilled, he responded, “I have no way of judging the reaction of frustrated middle-aged women.”
Crisp’s professional crisis coincided with the crisis of feminist Republicanism that culminated in the platform meetings that preceded the 1980 national convention in Detroit. In early July, conservative delegates succeeded in routing a last-ditch effort to save the ERA plank. The convention’s platform committee scrapped the party’s 40-year-old endorsement of the amendment and included language in the platform condemning alleged White House–directed pressure on anti-ERA states. The platform also included a sharpened antiabortion plank. Gone were the 1976 platform’s acknowledgment of party differences on the issue and call for “continuance of the public dialogue on abortion.” What was left was an endorsement of a constitutional ban and a call for the legislative prohibition of taxpayer-funded abortions.
At the final party meeting that she would attend as co-chair, Mary Crisp reacted to these developments with a tearful but defiant speech before the platform committee that startled her colleagues. She declared that the new ERA and abortion language would “bury the rights of over 100 million American women under a heap of platitudes.” She went on, “I cannot turn my back on these issues, and I feel compelled to do whatever is within my power to prevent these two tragedies from occurring.” She finished her speech to silence from most committee officials—Brock included—and a smattering of applause from the pro-ERA minority.
Crisp’s vow to reverse the platform committee’s actions proved futile. The denouement of Crisp’s Republican career, meanwhile, was swift. Her term as co-chair of the Republican National Committee ended on July 18. Less than a month later, she took a new position: co-chairwoman of John Anderson’s independent campaign.
The journey of Mary Crisp from party leader to party dissident to party outcast coincided with the ideological sorting that transformed the party system during the 1970s. Two implicit questions would recur every time a new controversy flared up over her tenure: What was the proper Republican position on a given issue, and should disagreeing with that position affect one’s bona fides as a Republican? Revealingly, Reagan himself couched his combative response to Crisp’s July 1980 farewell remarks in the language of partisan loyalty: “Mary Crisp should look to herself and find out how loyal she’s been to the Republican Party for quite some time.” The remark implied not only that conservative positions on women’s rights were the proper Republican positions, but also that a sufficient degree of apostasy on those issues amounted to partisan disloyalty.
For those, like Crisp, on the losing end of this factional conflict, the newly emerging ideological cast of American partisanship seemed synonymous with the breakdown of the party system itself. “Establishing purity tests for political views is contrary to the basic assumptions underlying our two-party system,” she wrote in a post-convention statement she never released. Crisp was correct that such tests were contrary to basic assumptions that had underlay the American system for decades. But those assumptions were no longer tenable.
The changing politics of women’s rights within the Democratic Party in 1980 highlighted the same dynamic. Feminist activists were an ascendant force within that party, one whose organizational clout had been on full display during a 1978 midterm convention mandated by party reformers. At the 1980 Democratic convention, most members and leaders within the feminist Coalition for Women’s Rights supported Ted Kennedy’s nomination challenge against President Jimmy Carter, and their policy agenda survived the collapse of Kennedy’s candidacy. Thanks to an effective whipping operation, the coalition secured not only the reaffirmation of existing planks supporting ERA ratification and opposing a constitutional amendment to ban abortion, but also managed to win convention floor votes on two planks opposed by Carter. The first explicitly opposed restrictions on federal funding for abortions. The second stated that the “Democratic Party shall withhold financial support and technical campaign assistance from candidates who do not support the ERA.” The latter item was, of course, just the kind of “purity test” that Crisp decried, on the very issue that had compelled her to exit her own party.
The simultaneous ascendance of feminist forces within the Democratic Party and antifeminist forces within the Republicans illustrated the logic of issue sorting in a two-party system. One party’s position change affected the other party’s approach, along with the strategic arguments that internal factions might make. As Gloria Steinem pointed out in the summer of 1980, the Republicans’ decision to stake out the right wing on women’s issues bolstered the rationale for the Democrats to speak forthrightly on them as a way of mobilizing women voters. And the further such sorting proceeded on a given issue, the more obvious was the necessity of choosing a side.
That logic, combined with the iron laws of first-past-the-post electoral systems from which all third-party bids suffer, crippled John Anderson’s ability to win the support of more feminist activists. A National Organization for Women official who personally supported Anderson wrote to Crisp in the fall of 1980 to explain why the organization had chosen not to endorse him, opting instead only to emphasize “total opposition” to Reagan. “The labor-feminist alliance is important, and there are hopes that it will thrive and expand,” she wrote. “John Anderson was viewed by many to be against labor reforms and was an unacceptable choice for the labor union advocates.”
In other words, the logic of a labor-liberal coalition inclined NOW toward continued advocacy within the Democratic Party rather than to third-party adventures or a pose of bipartisanship. The mirror of that coalition and logic was the Republican alliance of social and economic conservatives. Those same alliances endure today and continue to define our politics.
Mary Dent Crisp spent the next several decades mounting a rearguard effort to bolster feminist and pro-choice forces within the Republican Party. She ran the National Abortion Rights Action League and cofounded the National Republican Coalition for Choice. By the time of her death from a stroke in 2007, she had largely resigned herself to the extinction of a once venerable feminist tendency within the Republican camp.
If the death—or expulsion—of that tendency seemed protracted to her in the years after Reagan’s election, the initial mobilization against it in the 1970s seemed as remarkable for its swiftness as its intensity. In this way, Crisp’s ordeal was not only a harbinger of political gender battles to come, but also an experience that is currently recurring among never-Trump Republicans: the disorientation of a loyalist who watches the party as it transforms rapidly—and leaves them behind.
Reprinted with permission from The Polarizers: Postwar Architects of Our Partisan Era by Sam Rosenfeld, published by the University of Chicago Press. © 2017 by the University of Chicago. All rights reserved.",
                            'image' => 'assets/article5.jpg'
                        ],
                        ['id' => 6,
                            'title' => 'The So-Called Republican-FBI Split Is a Dem Fantasy',
                            'content' => "The Republican Party is the law and order party. That is not new, and it isn’t seriously contested. However, according to liberal media outlets such as HuffPost, Republicans are waging a “war on G-men.” The idea that Republicans are suddenly splitting from the FBI is a fantasy designed by the Democrats to attack a GOP strength and to distract from the growing revelations about anti-Trump maneuvering by a few senior FBI officials.
Republicans exposing the malfeasance of Hillary Clinton supporters at the top of the FBI’s ranks has hit a nerve. Democrats are afraid it could not only diminish their hopes that the Russia investigation will bring down President Trump but also perhaps flip the investigation into questions of senior FBI leaders manipulating the legal process to pursue Trump and help Clinton. As historian Victor Davis Hanson recently wrote in National Review, “the greatest irony of all” would be “a special counsel investigating what likely did not happen while ignoring what likely did — perhaps the greatest political scandal of the modern age.”
To me, it looks like former FBI deputy director Andrew McCabe, former FBI counterespionage section chief Peter Strzok, former associate deputy attorney general Bruce Ohr and perhaps others were anticipating a Clinton presidency. But they guessed wrong, and they got caught trying to impress Team Clinton. I’ve been in the swamp for more than 30 years. I know selfish career maneuvering when I see it. nyway, special counsel Robert S. Mueller III’s investigation and the related congressional inquiries are revealing the potential collusion between the Clinton campaign and the FBI, along with the Clinton campaign and Democratic National Committee paying an opposition researcher who was collecting dirt on Trump from Russians. Not the other way around. Since Democrats don’t have much to say, their response is to scream that Republicans are attacking the FBI. FBI line agents know better. Democrats know they are vulnerable, and they are nervous about what else may soon come to light in the pending FBI Inspector General’s report. Democrats won’t admit the severity of what might emerge, so they are deflecting. And the effort by Republican leaders in Congress to uncover the truth about what went on among a few senior FBI agents during the presidential campaign is hardly out of line or an affront to American law enforcement.
As a matter of perspective, to say the least, the Democrat coalition doesn’t include rank and file law enforcement. The Democrats are controlled by interest groups including public sector unions, trial lawyers, entertainment elites, hedge-fund billionaires and assorted angry left-wing grievance groups. But Republicans, by way of President Trump and Attorney General Jeff Sessions, have empowered the FBI and Justice Department to move away from Obama-era priorities. As Ron Hosko – president of the Law Enforcement Legal Defense Fund and former assistant director of the FBI – made clear in an op-ed late last year, “Trump’s law enforcement policies are a welcome improvement from Obama’s.”
Liberals may criticize Sessions for his no nonsense, tough on crime approach, but the numbers speak for themselves. As Sessions detailed in a USA Today op-ed last month, “In 2017, [the DOJ] brought cases against more violent criminals than in any year in recent decades. We charged the most federal firearm prosecutions in a decade. We convicted nearly 500 human traffickers and 1,200 gang members, and helped our international allies arrest about 4,000 MS-13 members. We also arrested and charged hundreds of people suspected with contributing to the ongoing opioid crisis.”
If Democrats and their allies in the media want to campaign on their support of law enforcement vs. that of the GOP, I’d like to see them try. Ultimately, it will catch up with the Democrats that while they shout about a split between the GOP and the FBI, nobody takes them serious as allies of law enforcement. The Trump administration is going after criminals in a way that President Barack Obama never did. Republicans are tougher on crime and more in line with the priorities of law enforcement than at any time in recent memory.",
                            'image' => 'assets\article6.jpg'
                        ]
    
	];
	$u = new post($db);
	$storiesFromDatabase = $u->update()->fetchAll();
	foreach($_GET as $key => $value)
	{
		if(substr($key, 0, 5) == "admin"){
			$admin = new admin();
			$admin->draw($storiesFromDatabase, $db);
			die();
		}
	}
	
    // Load page header
    $header = new mainHeaderTemplate();
	$content = $header->addHeader();
	if (empty($_GET[""])) {
		$content .= $header->addContent();
	}
	$header->setContent($content);
    echo $header->renderStatic();

?>
        <div class="row">

<?php
			// Process form data
			
			//RESETS THE ARTICLES IN THE DATABASE
			/*
			foreach($stories as $story){
				$formData = $story;	
				$r = $u->create($formData);
			}
			*/
			
			$storiesFromDatabase = $u->update()->fetchAll();
	
			$index = -1;
			foreach($stories as $story){
				$id = $story['id'];
				if (!empty($_GET['id']) && $_GET['id'] == $id) {
					$index = $id;
				}
			}
			

			
			if($index == -1){
				$content = new highlightedPostsTemplate();
				$modifiedStories = $storiesFromDatabase;
				for($i = 0; $i < count($modifiedStories); $i ++){	
					$modifiedStories[$i]['content'] = substr($modifiedStories[$i]['content'], 0, 128) . "...";
				}
				echo $content->data($modifiedStories)->renderList() . "</div>";
			}else{
				$post = new postTemplate();
				$post->drawContent($stories[$index - 1]);
			}
			    // Load page footer
	
			$footer = new mainFooterTemplate();
			echo  $footer->renderStatic();
			
?>
